### PR TITLE
Update schema value name and default values for Store

### PR DESCRIPTION
**Pull request by Pivotal-Jeff-Jun**

### CODE REVIEW

**Comment by RobC55** [comment]
@Pivotal-Jeff-Jun 
Is this only for v 0.4?

**Comment by russeta** [comment]
Reviewed and confirmed for commit.

**Comment by russeta** [comment]
@Pivotal-Jeff-Jun Have you committed this PR?  Status unclear.  Thank you.

**Comment by jncd** [comment]
Hi @Pivotal-Jeff-Jun 
We're assuming that this is a 0.4 beta only. We won't cherry-pick back to beta-3.

**Pull request merged**
