### PR TITLE
Fix formating and commands to be more consistent, add prerequsites se…

### PR DESCRIPTION
**Pull request by derwei**
…ction at the start so users will have everything they need to go through the install.

### CODE REVIEW

**Comment by jncd** [comment]
@derwei 
Could you take a look at these merge conflicts?

**Comment by derwei** [comment]
Hi @jncd ! I've fixed the conflicts. Please let me know if there's anything else I can help with or need to address.

**Comment by jncd** [comment]
Thanks so much @derwei 

Top tip: I think this isn't going to format correctly in your output. 

For VMware markdown (but not for github markdown), you need a blank line between stem sentence (with its colon) and the start of bullets or numbered steps. 

I'll push and we'll see.

Screen Shot 2021-10-04 at 2 19 09 PM

**Comment by derwei** [comment]
yup! you're right! looks like that broke things. let me push a fix

**Pull request merged**
