### PR TITLE
Remove API Scoring and Validation docs for 1.8

### PR DESCRIPTION
**Pull request by shrutiyer**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?
None

Does this need any other clean up?

### CODE REVIEW

**Review by csterwa — APPROVED** [review]

**Comment by snneji** [comment]
Hi @shrutiyer, is API Scoring and Validation component being removed from TAP? If so, we'll need to add a deprecation notice in the 1.7 release notes.

**Comment by snneji** [comment]
PR adding deprecation notice here: https://github.com/pivotal/docs-tap/pull/3168

**Comment by YugangW** [comment]
Hi @shrutiyer, [This plug-in topic](https://github.com/pivotal/docs-tap/blob/main/tap-gui/plugins/api-docs-getting-started.hbs.md) also contains numerous references to API Scoring and Validation docs. I was wondering could we get another PR to remove those links? Thanks!

**Comment by YugangW** [comment]
I've temporarily [commented out](https://github.com/pivotal/docs-tap/commit/196624e09e7613b6aa8e17ee77307afe19ed106d) the section containing the apix content and links.

**Comment by shrutiyer** [comment]
@YugangW I will update your PR with the edits. The plugin itself can stay since it can be used without APIx package. Just need to remove any references to package

**Pull request merged**
