### PR TITLE
adding known tap-gui security vulnerability to 1.3.1 docs

### PR DESCRIPTION
**Pull request by Braundo**

### CODE REVIEW

**Comment by Braundo** [comment]
@RichardJJG

**Comment by HenryBorys** [comment]
@Braundo I've been told we SHOULD NOT include unresolved CVEs in Release Notes. I've asked Jen about this one. I can't merge this until this uncertainty is resolved, hopefully very soon. I'll be watching until late tonight and will alert @RichardJJG about the issue.

**Review by Braundo — COMMENTED** [review]
Adjusted phrasing

**Comment by Braundo** [comment]
See Slack discussion regarding this documentation ([link](https://vmware.slack.com/archives/C02P2UZHJ4F/p1668469024155679)), including Jen's recommendation of publishing this communication. We'll also need to cherrypick this known vulnerability for every previous version of TAP as well.

**Pull request merged**
