### PR TITLE
Alv 1.0.2 version update

### PR DESCRIPTION
**Pull request by vudayani-vmw**
Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by RobC55** [comment]
@vudayani-vmw
Does this need to be cherry-picked to **TAP PROD 1.0**?

**Comment by vudayani-vmw** [comment]
Hi,

Is the 1.1 docs corresponding to TAP 1.0.1 release which is going out on Feb 8th ?
The PR<https://github.com/pivotal/docs-tap/pull/849> has changes for TAP 1.0.1 release.

From: Robert Cloud ***@***.***>
Date: Thursday, 3 February 2022 at 11:14 AM
To: pivotal/docs-tap ***@***.***>
Cc: Udayani V ***@***.***>, Mention ***@***.***>
Subject: Re: [pivotal/docs-tap] Alv 1.0.2 version update (PR #849)

@vudayani-vmw<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvudayani-vmw&data=04%7C01%7Cvudayani%40vmware.com%7Cbdab8e6c60a3465a50d608d9e6d83928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637794638633142085%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ofO%2BApedtdO4cZ7e0F%2F3HpaaAUjkhHvcS5%2Bzb2actLM%3D&reserved=0>
Does this need to be cherry-picked to TAP PROD 1.0?

—
Reply to this email directly, view it on GitHub<https://github.com/pivotal/docs-tap/pull/849#issuecomment-1028623133>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATCE3ZWZRLKQZVODVPMIHLLUZII3HANCNFSM5NN6B5IA&data=04%7C01%7Cvudayani%40vmware.com%7Cbdab8e6c60a3465a50d608d9e6d83928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637794638633142085%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y%2FzN3tPOK4q2l%2FI4staUFznU13mErk%2FeCbS%2BbhJm%2FrA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvudayani%40vmware.com%7Cbdab8e6c60a3465a50d608d9e6d83928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637794638633142085%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VziFbnMa5S2Nvwc%2BEVGvjUxK5ncT3WNyhX%2B7XTTJgEk%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvudayani%40vmware.com%7Cbdab8e6c60a3465a50d608d9e6d83928%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637794638633142085%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fZ3Msaobf6bQmWfKxN%2BBilB4XJDrrqkx8RYw7DWZXCY%3D&reserved=0>.

**Comment by RichardJJG** [comment]
@vudayani-vmw, the `1-0` branch is for TAP v1.0 docs, which includes the v1.0.1 patch. The `main` branch is for TAP v1.1.

@RobC55, we don't have a branch called `TAP PROD 1.0`. If you suggest an engineer cherry-picks to `TAP PROD 1.0`, nothing will happen.

**Comment by RichardJJG** [comment]
@vudayani-vmw just told me in Slack that these changes need cherry-picking to `1-0`.

**Pull request merged**
