### PR TITLE
chore: rename scst-store to metadata-store

### PR DESCRIPTION
**Pull request by SebastianOsuna**

### CODE REVIEW

**Comment by Manifaust** [comment]
This is related to TANZUSC-740

**Comment by jncd** [comment]
Hi @SebastianOsuna 
Does this apply to the beta-4 docs too? 
I can copy your changes to the beta-4 docs too. Just let me know asap. Thanks!

**Comment by Manifaust** [comment]
@jncd this change does **not** apply to beta-4. This change only applies to GA.

**Comment by jncd** [comment]
@Manifaust Thanks for the clarification.

**Pull request merged**
