### PR TITLE
docs: update vs code docs for windows support

### PR DESCRIPTION
**Pull request by kiwi-bui**

### CODE REVIEW

**Comment by snneji** [comment]
Hi @kiwi-bui, does this apply to any TAP versions other than 1.3?

**Comment by kiwi-bui** [comment]
@snneji This should work with any TAP version, but the user will need the 0.9.0 or later of the VSCode extension.

**Comment by vrabbi** [comment]
this works on linux as well. i have tested anbd been using it seamlessly on ubuntu 18, 20, and 22

**Comment by kiwi-bui** [comment]
@vrabbi Thank you for the feedback, I'll let my team know!

**Comment by RichardJJG** [comment]
@kiwi-bui, please submit a new PR that references Linux if you verify that it's definitely okay to tell customers that Linux is supported.

**Pull request merged**
