### PR TITLE
Add instructions for patch versions

### PR DESCRIPTION
**Pull request by neil-hickey**
https://jira.eng.vmware.com/browse/TANZUSC-4314

### CODE REVIEW

**Comment by RichardJJG** [comment]
We received your PR after the Doc Freeze date. We are currently working on release tasks, and we will review your PR as soon as we are able. Unfortunately, this might mean that your PR content will not be published until after the release. Going forward, to ensure that your PR changes are published on release day, please submit such PRs no later than 23:59 UTC-8 on the [Doc Freeze date](https://confluence.eng.vmware.com/pages/viewpage.action?pageId=789919969).

**Comment by RichardJJG** [comment]
@neil-hickey, which branches do you want a writer to cherry-pick this change back to, if any?

**Comment by neil-hickey** [comment]
hey @RichardJJG / @YugangW could this be back-ported to the 1.5.x docs? I am happy to do it also if needed, let me know!

**Comment by YugangW** [comment]
Hello, @neil-hickey  Could you please create a new PR targeting the branch 1-5-4? I couldn't cherry-pick this PR back to 1.5.x due to significant docs restructuring in v1.6, including the addition of new files and changes to file names. Thanks!

**Pull request merged**
