### PR TITLE
appsso: clarify response_type code with CORS

### PR DESCRIPTION
**Pull request by sarahwalther**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

- 1.5.3
- 1.4.8
- 1.4.7

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

### CODE REVIEW

**Review by mamachanko — APPROVED** [review]

**Comment by YugangW** [comment]
Hi @sarahwalther, Are these changes also applicable to 1-5-4, 1-6-1, and 1-6-2? Thanks!

**Comment by mamachanko** [comment]
@YugangW yes, they are!

**Comment by YugangW** [comment]
Hi @sarahwalther @mamachanko I was unable to cherry-pick this change back to 1-4-7 and 1-4-8. It looks like those topics do not exist in these two branches?

**Comment by mamachanko** [comment]
> Hi @sarahwalther @mamachanko I was unable to cherry-pick this change back to 1-4-7 and 1-4-8. It looks like those topics do not exist in these two branches?

@YugangW You are right! That's an oversight. Off the cuff, my best idea is to add the "note" from this PR to the "Known limitations" section in the 1.4.x line, i.e. [here](https://github.com/pivotal/docs-tap/blob/791204e289c2793bda507bdf4d59ba7a40c8419b/app-sso/known-issues/index.hbs.md?plain=1#L1). What do you think?

**Pull request merged**
