### PR TITLE
Corrected tanzu insight command

### PR DESCRIPTION
**Pull request by miketeve**
Missing tanzu prefix

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by a-peek4** [comment]
Thanks @miketeve Does this apply to any other versions besides 1.3?

**Comment by miketeve** [comment]
Sorry, it does apply to 1.2 as well!

From: Alison Peek ***@***.***>
Date: Monday, September 19, 2022 at 2:07 PM
To: pivotal/docs-tap ***@***.***>
Cc: Mike Tevebaugh ***@***.***>, Mention ***@***.***>
Subject: Re: [pivotal/docs-tap] Corrected tanzu insight command (PR #1578)

Thanks @miketeve<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmiketeve&data=05%7C01%7Cmtevebaugh%40vmware.com%7Cccc904ed31cd4efa801108da9a83021f%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637992184716009293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9LnigS5UD08wUwF4k1Z3S926Y0ombiM1zG%2BtedHtR3Y%3D&reserved=0> Does this apply to any other versions besides 1.3?

**Comment by miketeve** [comment]
@a-peek4 are you able to also apply this to 1.2?  lmk if you need me to make another pr

**Comment by HenryBorys** [comment]
@miketeve @a-peek4 No need. I just made the changes in 1.2.2 and will push it live. Thanks.

**Pull request merged**
