### PR TITLE
Update how to scale services toolkit

### PR DESCRIPTION
**Pull request by Samze**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?
1.9.0

### CODE REVIEW

**Comment by Samze** [comment]
Keys not yet agreed, do not merge.

**Comment by Samze** [comment]
@snneji is there a standard way that these scalability resource package values are documented in component docs, or is it fine for them just to be in the scalability section?

**Comment by snneji** [comment]
Hi @Samze, it's fine for these docs to just be on the scalability page.

**Comment by Samze** [comment]
@snneji this is ready for review 👍

**Pull request merged**
