### PR TITLE
Update dependencies.hbs.md

### PR DESCRIPTION
**Pull request by johnnyr0x**
Updated the dependencies for TAP 1.3. Added jammy stacks.

### CODE REVIEW

**Comment by johnnyr0x** [comment]
@matthewmcnew - I was not able to confirm a few items so made my best guess (e.g. for the stacks I viewed the versions updated on 9/7). Could you confirm the following?

- Stack versions included
- PHP version
- Java / Java native version (I believe there was a recent PR to fix CVE's?)

**Comment by RichardJJG** [comment]
@johnnyr0x, please take this out of draft when it's definitely ready for merging.

**Comment by tylerphelan** [comment]
we might have merged something similar! you might need to rebase.

java version: 7.5.0
Php version: 1.2.0
stack versions: no sure

**Comment by matthewmcnew** [comment]
Stack Versions: 
```
tanzu-base-bionic-stack/build: 1.2.17-base-cnb
tanzu-base-bionic-stack/run: 1.2.17-base-cnb
tanzu-base-ubuntu-2204-stack/build: 0.1.1
tanzu-base-ubuntu-2204-stack/run: 0.1.1
tanzu-full-bionic-stack/build: 1.3.88-full-cnb
tanzu-full-bionic-stack/run: 1.3.88-full-cnb
tanzu-full-ubuntu-2204-stack/build: 0.1.1
tanzu-full-ubuntu-2204-stack/run: 0.1.1
tanzu-tiny-bionic-stack/build: 1.3.72-tiny-cnb
tanzu-tiny-bionic-stack/run: 1.3.72-tiny-cnb
tanzu-tiny-ubuntu-2204-stack/build: 0.1.1
tanzu-tiny-ubuntu-2204-stack/run: 0.1.1
```

**Comment by snneji** [comment]
Closing as this information was added in #1730

**Pull request closed without merging**
