### PR TITLE
Create Iterate on your function

### PR DESCRIPTION
**Pull request by sheltoG**
Would it be possible to make the functions beta section a folder and add this file as a drop down item within it?

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by RichardJJG** [comment]
@sheltoG, yes, we can nest topics. Is this content for just TAP v1.2 onwards?

**Comment by sheltoG** [comment]
We can nest and add this content for TAP 1.1 docs as well. Thank you!

**Comment by sheltoG** [comment]
My apologies, I was out last week. 

1.  We can use "Configure the Tanzu Developer Tools extension".
2. Step 3 is a note that may effect some users.
3. At the bottom of the VS code window there is text that will either say Live Update Started or Live update stopped.
4. The option they would select would be Tanzu: Live Update Stop.

**Comment by snneji** [comment]
Hi, just a quick followup question in reference to your answer to question 4: would they also have the option "Tanzu: Live Update Continue" in the command palette?

**Comment by sheltoG** [comment]
You only have two commands to choose from: Tanzu: Live Update Start and Tanzu: Live Update Stop. There is a section of the docs this is referenced from: [(https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.1/tap/GUID-getting-started.html#live-update-your-application-7)

**Pull request merged**
