### PR TITLE
Add service registry docs

### PR DESCRIPTION
**Pull request by maly7**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

None, these docs are for TAP 1.7.0

### CODE REVIEW

**Comment by snneji** [comment]
Hi @maly7, could you also add this as a new component in the [New components](https://github.com/pivotal/docs-tap/blob/7bb467951e2bc8da1ea9912da63198064d5f0b85/release-notes.hbs.md?plain=1#L20) section of the release notes. Thanks!

**Comment by RichardJJG** [comment]
@maly7, are these docs ready to leave draft mode now?

**Comment by candicenonsense** [comment]
@RichardJJG If your team thinks it looks good enough, we're happy to let it leave draft mode - do you want the New Component add in another PR ?  (Paul's out today so I am covering)

**Comment by RichardJJG** [comment]
@candicenonsense, yes, please submit any more docs content you have as a new PR, thanks.

**Comment by RichardJJG** [comment]
@candicenonsense, do you know if many more topics are coming? I ask because, if not, it would make sense for me to move topics out of the getting-started folder. The TAP side nav is already very crowded, so I'd like to simplify where practical. If many more topics are coming, then I understand that the Getting Started division makes sense.

**Comment by maly7** [comment]
@RichardJJG As of right now, I can't think of any other topics that need to go into the getting started folder. If it simplifies things, then it makes sense to remove the division. I mostly added it to follow what seemed like an existing pattern.

**Comment by RichardJJG** [comment]
> @RichardJJG As of right now, I can't think of any other topics that need to go into the getting started folder. If it simplifies things, then it makes sense to remove the division. I mostly added it to follow what seemed like an existing pattern.

Thanks, and it was sensible to follow the pattern -- I just want to make the side nav less crowded as the TAP docs grow and grow.

**Comment by RichardJJG** [comment]
@maly7, extra steps are needed beyond [writing this YAML](https://github.com/pivotal/docs-tap/pull/2877/files#diff-bd2f9293944fe5d2c379e69dc5fec2e99d8bf582ff67fc0f07f14fc505bfa0b7R43), right?

I'm guessing that the user also

1. Needs to add the YAML to an existing file or create a new YAML file and name it something obvious.
1. Apply the YAML file changes by running some command in Tanzu CLI that includes the YAML file name.

**Comment by maly7** [comment]
> @maly7, extra steps are needed beyond [writing this YAML](https://github.com/pivotal/docs-tap/pull/2877/files#diff-bd2f9293944fe5d2c379e69dc5fec2e99d8bf582ff67fc0f07f14fc505bfa0b7R43), right?
> 
> I'm guessing that the user also
> 
> 1. Needs to give the YAML file an obvious name.
> 2. Apply the YAML file changes by running some command in Tanzu CLI that includes the YAML file name.

Correct. It would seem I completely forgot to write that section. I'll submit a PR to fix that.

**Pull request merged**
