### PR TITLE
Apps Plugin: Updating docs to add a working example

### PR DESCRIPTION
**Pull request by warango4**
There is an error/problem with official petclinic source code related to buildpack (mvn build failure).
- Changed source repo to point to app accelerator example.
- Used latest tag (tap-1.1)

Signed-off by: Wendy Arango warango@vmware.com

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by a-peek4** [comment]
@warango4 Please ping us when this is out of draft state and ready to merge. Thanks!

**Comment by RichardJJG** [comment]
Thanks, @warango4, is this change just for the v1.2 TAP docs (main branch) or is it for the v1.1 docs also (1-1 branch)?

**Comment by heyjcollins** [comment]
This looks good to me. 
If there's no other questions to resolve, could someone please accept this MR?

**Comment by a-peek4** [comment]
Thanks @warango4 and @heyjcollins

**Pull request merged**
