### PR TITLE
deprecate git_implementation for scc [TSCC-302]

### PR DESCRIPTION
**Pull request by pivotal-todd-ritchie**
No other branches, just for 1.6

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
I would expect this to touch a few other mentions of git-implementation:
### In the scc/azure docs:
- [The discussion of gitImplementation](https://github.com/pivotal/docs-tap/blob/main/scc/azure.hbs.md#-gitops-read-implementation-templates)
- The sentence: `Azure DevOps requires Git clients to support multi-ack.`
- All the code examples with gitImplementation

**Comment by waciumawanjohi** [comment]
Mention of gitImplementation deprecation in the ootb-template-reference: https://github.com/pivotal/docs-tap/blob/main/scc/ootb-template-reference.hbs.md

**Comment by waciumawanjohi** [comment]
There are a few other pages that mention gitImplementation (workload-reference.hbs.md, building-from-source.hbs.md, delivery-with-flux.hbs.md, ootb-delivery-reference.hbs.md)

**Comment by pivotal-todd-ritchie** [comment]
Thanks @waciumawanjohi, I'll make those updates

**Pull request merged**
