### PR TITLE
Excluded policy controller in TAP 1.3+ installation

### PR DESCRIPTION
**Pull request by kkavitha**
The change has to be added in the following TAP versions:
1. 1.4
2. 1.3.0
3. 1.3.1

cc: @elfotografo007 @derwei @dherbrich @DennyHoang

### CODE REVIEW

**Comment by kkavitha** [comment]
The change has to be added in the following TAP versions:

1.4
1.3.0
1.3.1

**Comment by RichardJJG** [comment]
Thanks, @kkavitha

**Comment by derwei** [comment]
hi @RichardJJG - would it be possible to get this into the 1-3-0 branch as well?

Thanks!!

**Comment by RichardJJG** [comment]
@derwei, yes, we'll cherry-pick to all versions that @kkavitha requested. The Tracker story for this PR is [here](https://www.pivotaltracker.com/story/show/183661722).

**Comment by derwei** [comment]
@RichardJJG awesome! thank you so much!! =)

**Pull request merged**
