### PR TITLE
updating plugin install instructions

### PR DESCRIPTION
**Pull request by msrinivasssa**
Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by RichardJJG** [comment]
@msrinivasssa, do these changes apply to v1.0 also?

CC @piachakra because I need go-ahead from her before we merge changes to installing topics that affect TAP v1.0.

**Comment by msrinivasssa** [comment]
> @msrinivasssa, do these changes apply to v1.0 also?
> 
> CC @piachakra because I need go-ahead from her before we merge changes to installing topics that affect TAP v1.0.

No. This is applicable only for 1.1.0

**Comment by RichardJJG** [comment]
Okay, thanks, @msrinivasssa -- I've merged. CC @piachakra.

**Comment by a-peek4** [comment]
@msrinivasssa Can you clarify if the user runs both of the following commands:
```
tanzu plugin install --local cli all

tanzu plugin install --local cli/standalone all
```

Do these commands install a different CLI?

**Comment by msrinivasssa** [comment]
> @msrinivasssa Can you clarify if the user runs both of the following commands:
> 
> ```
> tanzu plugin install --local cli all
> 
> tanzu plugin install --local cli/standalone all
> ```
> 
> Do these commands install a different CLI?

Yes user has to run both the clis. They install different plugins

**Pull request merged**
