### PR TITLE
Add new Known Issue for Service Bindings

### PR DESCRIPTION
**Pull request by st3v**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

`1.7.0` and `1.7.1`

fyi @teddyking

### CODE REVIEW

**Comment by teddyking** [comment]
lgtm!

**Comment by st3v** [comment]
Thanks for merging, @YugangW! Just to make sure, are you still planning on cherry-picking this in the `1.7.0` and `1.7.1` branches?

**Comment by YugangW** [comment]
Hi @st3v, @kcoriordan will do the cherry-pick for you as part of the editing work.

**Comment by kcoriordan** [comment]
@st3v 
production branch is now 1-7-1.
and next patch release is 1-7-2 - still in staging.
main is upcoming 1-8 release

should this content appear in release notes for all?

**Comment by teddyking** [comment]
Hi @kcoriordan - this change only needs to apply for 1-7-0 and 1-7-1. We are planning to fix it for 1-7-2 and 1-8. Thanks!

**Comment by st3v** [comment]
@teddyking - @kcoriordan and I talked about this offline and said we would have a Known Issue for this documented as part of the release notes for:
* 1.7.1
* 1.7.2 (we will remove that note as soon as we merge our fix)
* 1.8.0 (we will remove that note as soon as we merge our fix)

**Pull request merged**
