### PR TITLE
Update Store links in TOC and Additional

### PR DESCRIPTION
**Pull request by Manifaust**
Add .hbs extension to Store links in TOC and Additional page

Merge into `main`, `1-3-0`, `1-3-1`, and `1-2-2`.

### CODE REVIEW

**Comment by Manifaust** [comment]
No I did not notice any problems with the functionality in the past.

This change was just to make clicking it inside my VSCode editor a bit easier.

**Comment by HenryBorys** [comment]
Sounds good. I don't see any reason not to do this throughout the TOC for the same advantage in clicking links in VS Code.

**Comment by HenryBorys** [comment]
In other words, I'll do that while I'm at it.

**Comment by HenryBorys** [comment]
Not as simple as I thought, because of all the App-SSO content, so leaving that alone. But the changes @Manifaust made, look fine. Thanks.

**Pull request merged**
