### PR TITLE
Document metadata store's ingress

### PR DESCRIPTION
**Pull request by SebastianOsuna**

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @SebastianOsuna, should I copy any of these changes to the v1.0 docs?

**Comment by HenryBorys** [comment]
@SebastianOsuna Looks like you've created a new topic, ingress-multi-cluster.md, but you have no title tag for it. What is the title supposed to be? Right now it looks like you might have intended Ingress support to be the title, but I want to make sure. Please let me know. And how do I reach you in Slack or email? I couldn't find you. Thanks.

**Comment by HenryBorys** [comment]
@SebastianOsuna Ah, no worries, I figured out your intended page title for ingress-multicluster.md from your links in the other pages.

**Comment by HenryBorys** [comment]
@SebastianOsuna BTW, We use only dashes, not underscores in file names, so I'm changing those back and fixing any links.

**Pull request merged**
