### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by chaomonica**
Which other branches should this be merged with (if any)? none (only 1-0)

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks!

**Comment by RichardJJG** [comment]
A few questions:

1. What does "jobs/pods" mean? "jobs and pods"? "jobs or pods"? Is "jobs" just a synonym for "pods" here?

2. What is meant by the example error "ScanPolicy defined"? Is it an error that it is defined or not? Is ""ScanPolicy defined" the name of a common error? We need to delete this or add a bit more detail to this example.

3. "logs are missing error details with a `git clone` error or error fetching scanner logs"
I don't know what this means. I'm guessing it means:
"Running `git clone` sometimes causes errors that are only partially described in the event log. The same is true for errors arising from trying to fetch scanner logs."

**Comment by chaomonica** [comment]
@RichardJJG If the below looks better, I can open another pull request to fix the wording.
1. It is two jobs and two jobs.  Currently instead of a single job and a single pod running, we are getting duplicates.
2. Oops, my mistake, it should be `ScanPolicy undefined`. 
3. "Errors that arise through either `git clone` or when trying to fetch scanner logs are only partially described in the event log."

**Comment by RichardJJG** [comment]
> @RichardJJG If the below looks better, I can open another pull request to fix the wording.
> 
> 1. It is two jobs and two jobs.  Currently instead of a single job and a single pod running, we are getting duplicates.
> 2. Oops, my mistake, it should be `ScanPolicy undefined`.
> 3. "Errors that arise through either `git clone` or when trying to fetch scanner logs are only partially described in the event log."

Yes, please open another PR -- thanks!

**Pull request merged**
