### PR TITLE
Document IntelliJ 'corrupted launch config' workaround

### PR DESCRIPTION
**Pull request by kdvolder**
Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

All branches after 1.3.1 so I think that means 1-3-2 and main.

### CODE REVIEW

**Comment by kdvolder** [comment]
Related Jira: https://jira.eng.vmware.com/browse/TD-1064

**Comment by a-peek4** [comment]
Hi @kdvolder We received your PR after the doc freeze date. We are currently working on release tasks, and we will review your PR as soon as we are able. Unfortunately, this may mean that your PR will not be published until after the release. Going forward, to ensure that your PRs are included on release day, please submit them no later than 23:59 UTC-8 on the [doc freeze date](https://confluence.eng.vmware.com/pages/viewpage.action?pageId=789919969).

**Comment by kdvolder** [comment]
Sure, I understand, and thanks for doing whatever you can to get it in. If it gets in before release that is great. If it happens after release so be it, it really isn't a big deal. 

> please submit them no later than 23:59 UTC-8 on the [doc freeze date]

We will try, but really, the PR was submitted as soon as it was ready. While we may hope/try to put all changes in before a certain date, this can't always be done. 

I would assume that since docs are essentially just web-pages the content of which we can 'in theory' update at any time, it shouldn't really stop us from submitting changes after the 'freeze date'. Even after a product was released, I beleave we should be stll be able to update its docs as we discover the need to do so.

If that isn't the case and docs become 'read only' after release/freeze, then I can resubmit a PR for 1.3.2 branch (in fact I considered doing that, but when I look at 1.3.2 branch's content it looks like the various bits and pieces from 1.3.1 that need to be cherry picked may not yet be in that branch... so I decided instead to do the PR against 1.3.1 which seems to have most up-to-date content).

Let me know if need/want me to rebase PR against 1.3.2 branch if its too late for 1.3.1 doc changes.

**Comment by RichardJJG** [comment]
@kdvolder, you're correct in that the docs are alive and subject to change until we archive them when the relevant product version leaves general support.
The Docs Freeze period exists because the writers need time to get through the last of the PR backlog and prepare to safely piublish.

**Pull request merged**
