### PR TITLE
Updated apps plugin command reference with latest supported parameters for apply,update and create subcommands

### PR DESCRIPTION
**Pull request by suarezjulian**

### CODE REVIEW

**Review by heyjcollins — APPROVED** [review]

**Comment by jncd** [comment]
Hi @suarezjulian 

Do you want this to appear in the beta-4 docs too?

+ https://docs-staging.vmware.com/en/Tanzu-Application-Platform/1.0/tap/GUID-cli-plugins-apps-command-reference-tanzu_apps_workload_apply.html

+ https://docs-staging.vmware.com/en/Tanzu-Application-Platform/1.0/tap/GUID-cli-plugins-apps-command-reference-tanzu_apps_workload_create.html

+ https://docs-staging.vmware.com/en/Tanzu-Application-Platform/1.0/tap/GUID-cli-plugins-apps-command-reference-tanzu_apps_workload_update.html

**Comment by suarezjulian** [comment]
thanks @jncd it is fine to let this change only in post-beta4 docs

**Comment by heyjcollins** [comment]
@jncd - 
Just to be clear - these changes should ONLY be viewable in TAP GA (v1.0.0) docs and above. --- I'm pretty sure that's been done, but wanted to make certain so leaving this comment.

**Comment by jncd** [comment]
@heyjcollins Thanks! That's what I inferred and did... but I really appreciate the confirmation.

**Pull request merged**
