### PR TITLE
Split ingress multicluster

### PR DESCRIPTION
**Pull request by Manifaust**
This change is a follow up to an earlier change which created a new Store multicluster-setup.hbs.md. Since the new doc exists, we can now remove the multicluster portion of an older doc ingress-multicluster.hbs.md.

Also, I improved some parts of the new Store multicluster-setup.hbs.md.

Please merge this into 1.4 (main), 1.3, and 1.2.

If you have problems merging let me know, I can help.

### CODE REVIEW

**Comment by YugangW** [comment]
Hi @Manifaust, It looks like there are some conflicts in `scst-store/additional.hbs.md`. Could you please help to resolve it?

**Comment by Manifaust** [comment]
@YugangW thanks for letting me know. I have resolved it now.

**Comment by YugangW** [comment]
@Manifaust Thanks for your quick response! I tried to cherry-pick this commit to 1.3 and 1.2 but encountered many merge conflicts... Would you mind sending two separate PRs against `1-3-1` and `1-2-2`?

**Comment by Manifaust** [comment]
Okay I'll do that

**Comment by YugangW** [comment]
Thanks a lot!

**Pull request merged**
