### PR TITLE
Runtime resources: Resource metric section

### PR DESCRIPTION
**Pull request by Smorenoz**

### CODE REVIEW

**Comment by chinigo** [comment]
Copyedited:


```
The overview card displays the user-configured resource limits on the Pod, defined as per the Kubernetes documentation for [Configuring Pods Limits](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/). These limits do not represent actual real-time resource usage. (The Live View Plugin can help you with that!)

Each container displays its resource limits, if defined:

![Container limits](images/runtime-resources-container-metrics-pod-page.png)

Pods display the sum of the limits of all their containers. If any container fails to specify a limit, both it and its Pod will be presented as requiring "Unlimited" resources.

![Pod limits overview](images/runtime-resources-pod-limits-overview.png)

Namespace-level resource limits (e.g. [default memory limits](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/) and [default CPU limits](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/)) are not considered as part of these calculations.
```

**Comment by chinigo** [comment]
Oh nice there's a link to the the ALV docs. Is this the intended hyperlink?

`app-live-view-springboot.md#a-id"threads-page"a-threads-page`

(note the "threads-page", is that right?)

If that's correct, this is great, please ship!

**Comment by Smorenoz** [comment]
Hey Michael! Yeah, `threads-page` is where they talk about CPU usage and right under that section is the `memory-page`

**Comment by chinigo** [comment]
Cool, thanks @Smorenoz .

**Pull request merged**
