### PR TITLE
Update version of app live view to 1.0.2

### PR DESCRIPTION
**Pull request by vudayani-vmw**
Which other branches should this be merged with (if any)?
This change is for TAP 1.0.2

### CODE REVIEW

**Comment by RichardJJG** [comment]
@vudayani-vmw, in these commands `1.0.2` refers to the Tanzu Application Platform version the user is on, right? And so the number in the command needs to be, for example, `1.0.1` if the user is on Tanzu Application Platform v1.0.1?

**Comment by vudayani-vmw** [comment]
@RichardJJG The version `1.0.2` here refers to Application Live View packages. The component package versions are independent of the Tanzu Application Platform version. For example, we had shipped App live View v1.0.1 for TAP 1.0.0 release.

**Comment by RichardJJG** [comment]
@vudayani-vmw, okay, thanks, so the commands will work regardless of the TAP version the user is on (v1.0.0, v1.0.1, or v1.0.2)?

**Comment by vudayani-vmw** [comment]
@RichardJJG , The App Live View  `1.0.2` is shipped with TAP v1.0.2. If the user is on TAP (v1.0.0, v1.0.1) they have to upgrade the TAP repository to 1.0.2 version so that new package versions are available and then upgrade the component packages.

**Comment by RichardJJG** [comment]
Okay, @vudayani-vmw, we won't merge this until the TAP v1.0.2 release.

CC @a-peek4 and @piachakra

**Pull request merged**
