### PR TITLE
better clarity on example values for `dockerfile-based-builds.hbs.md`

### PR DESCRIPTION
**Pull request by djschny**
The idea here is to make it more clear which values are example values and to distinguish between example values and what they mean instead using the same value for all examples.

### CODE REVIEW

**Comment by RichardJJG** [comment]
@djschny, a writer should cherry-pick this back as far as possible, right?

**Comment by djschny** [comment]
> @djschny, a writer should cherry-pick this back as far as possible, right?

I don't know. That's up to you and your internal procedures.

**Comment by RichardJJG** [comment]
@djschny, a writer shouldn't cherry-pick backwards if SCC is so deceptively different in some earlier version that this placeholder change would be misleading. Your response suggests that's not the case, though, so a writer will cherry-pick backwards as far as the code examples exist.

**Comment by djschny** [comment]
Once again, I don't believe that is the responsibility of the contributor. The PR is for the main branch. If there were differences/deltas on older versions, that should be separate PRs to there. Cherry picking is dangerous and clunky.

**Comment by RichardJJG** [comment]
@djschny, there should, indeed, be separate PRs if the PR content must be modified to apply to earlier versions of the product.

**Pull request merged**
