### PR TITLE
Add section for Tanzu buildpacks

### PR DESCRIPTION
**Pull request by arjun024**
Resolves https://github.com/pivotal-cf/tanzu-buildpacks/issues/383

### CODE REVIEW

**Comment by arjun024** [comment]
@johnnyr0x - please review

**Comment by a-peek4** [comment]
@arjun024 Did you want me to merge this? I see you asked for a review

**Comment by johnnyr0x** [comment]
@arjun024 - looks good to me. 

@a-peek4 - yes, please merge if it looks good to you.

**Comment by kcoriordan** [comment]
@arjun024 
Would it ok to move this section as a sub section of TBS right underneath?
Is my understanding that only TBS users use the build packs?
If the packaging has changed -  'builders, stacks, and buildpacks are packaged separately from Tanzu Build Service, but are included in the same Tanzu Application Platform profiles as Tanzu Build Service.' - Does this need a release notes entry?

**Comment by johnnyr0x** [comment]
@kcoriordan - thanks for checking. We were asked to make this new section to give more visibility to buildpacks since they aren't just a component of TBS anymore after 1.6. All TAP users use buildpacks by default in the build phase of the supply chain (not just TBS users).

I confirmed with @mgibson1121. @mgibson1121 - feel free to add your comments.

**Comment by mgibson1121** [comment]
Yes, @kcoriordan, although customers use buildpacks through TBS, we struggle with discoverability for buildpacks as a component for customers to find documentation on how to configure them. Additionally, as John mentions, they are now separate packages rather than being included as part of TBS. So it can be said they are a distinct component.

**Comment by kcoriordan** [comment]
Does this need to be called out [here ](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.7/tap/about-package-profiles.html) in the _Installation profiles in Tanzu Application Platform v1.7_ (scroll to bottom of page) topic?

And did you reach a decision on whether we need a release note for this change? 
@mgibson1121 @johnnyr0x

**Comment by johnnyr0x** [comment]
Thanks Kay. Yes - good thought! Can we add Tanzu Buildpacks to the [installation profiles tables](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.7/tap/about-package-profiles.html#installation-profiles-in-tanzu-application-platform-v17-1) and check the boxes full, iterate, and build.

We don't need a release note as it happened in 1.6.

**Comment by kcoriordan** [comment]
Are the Tanzu Buildpacks only available/installed as part of the profiles or can Tanzu Buildpacks be installed individually or collectively as a separate package? So can they be installed using `tanzu package install` or only all available as part of an installation profile.


Also, should Tanzu Buildpacks be mentioned anywhere else, so right now we're just saying, they exist, go look here for doc, but should we add something to Get Started guide or somewhere else to show where in the lifecycle they will be referenced/used. 

Should we list the available Tanzu Buildpacks? So these:

      ```
base-jammy-builder-lite.buildpacks.tanzu.vmware.com  base-jammy-builder-lite
      base-jammy-stack-lite.buildpacks.tanzu.vmware.com    base-jammy-stack
      dotnet-core-lite.buildpacks.tanzu.vmware.com         dotnet-core-lite
      go-lite.buildpacks.tanzu.vmware.com                  go-lite
      java-lite.buildpacks.tanzu.vmware.com                java-lite
      java-native-image-lite.buildpacks.tanzu.vmware.com   java-native-image-lite
      nodejs-lite.buildpacks.tanzu.vmware.com              nodejs-lite
      python-lite.buildpacks.tanzu.vmware.com              python-lite
      ruby-lite.buildpacks.tanzu.vmware.com                ruby-lite
      web-servers-lite.buildpacks.tanzu.vmware.com         web-servers-lite
```

**Comment by kcoriordan** [comment]
@mgibson1121 ^

**Comment by johnnyr0x** [comment]
1. Yes they can be installed individually following the instructions that Matt added to this PR https://github.com/pivotal/docs-tap/pull/2996. Do you think we should move this to a section under the Tanzu buildpacks or keep it where Matt added it?
2. Good thoughts. I went through getting started and I am not sure. The [deploy a workload section](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap/getting-started-deploy-first-app.html#procedure-4) is where buildpacks are used, but not through explicit commands except through variables shown in the workload.yaml file. For example you would configure your workload.yaml file with the parameters highlighted [here](https://docs.vmware.com/en/VMware-Tanzu-Buildpacks/services/tanzu-buildpacks/GUID-web-servers-web-servers-buildpack.html#how-to-use-in-tap) if you want to build a web servers application. If the users follow the getting started section, they won't have any visibility to that because it has them generating the workload.yaml through the application accelerator. I am open to adding this information in other places though. Let me know what you think.
3. I am open to adding something. We show this information [here](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap/about-package-profiles.html#language-and-framework-support-in-tanzu-application-platform-2), but I would be OK adapting that or copying it for a buildpacks page. 

I'm happy to jump on a quick call tomorrow morning if that would make things easier. Thank you for diving into these and pushing to make our docs better!

**Comment by kcoriordan** [comment]
I think if Buildpacks are packaged separately from TBS, it might be good to have the install/upgrade doc separated from TBS also and under the  new Buildpacks section.

**Comment by kcoriordan** [comment]
@johnnyr0x @mgibson1121 
I setup a quick doc sync for Buildpacks tomorrow - pls counter to a time that suits.

**Pull request merged**
