### PR TITLE
Remove Light and Initial Multi-cluster docs

### PR DESCRIPTION
**Pull request by krisapplegate**
Which other branches should this be merged with (if any)?
1.1+

### CODE REVIEW

**Comment by RichardJJG** [comment]
Are we okay to merge, @piachakra?

**Comment by krisapplegate** [comment]
Confirmed with @mpriamo that this is good to merge now.

**Comment by RichardJJG** [comment]
Thanks, merged!

**Comment by YugangW** [comment]
Hi @krisapplegate, Thanks for the PR. I removed the `Reference` heading in `toc.md` as a temporary measure to fix the build failure. If you would prefer, an other way to fix this is to create a new file in the repo (e.g., `reference.md`) that the `Reference` heading can link to in the toc. I can create this blank file but might need your help to fill in some content if you prefer this method. Thanks!

**Pull request merged**
