### PR TITLE
Tools now support non-default namespace

### PR DESCRIPTION
**Pull request by hnandiwada**
https://github.com/vmware-tanzu-private/vscode-tanzu-tools/pull/99

Authored-by: Harsha Nandiwada <hnandiwada@vmware.com>

### CODE REVIEW

**Comment by RobC55** [comment]
@hnandiwada
Is this commit only for TAP v0.4?

**Comment by jncd** [comment]
Hi @hnandiwada 
We're assuming that you only intended this for v0.4.

**Comment by hnandiwada** [comment]
@jncd Yes, only for beta 4.

**Comment by jncd** [comment]
Thanks! @hnandiwada It's always best to let us know in the PR comments.

(I got in trouble from another team today because they _wanted_ their PR copied to beta-3 ¯\_(ツ)_/¯ )

**Comment by hnandiwada** [comment]
Ah, sorry about that @jncd! Will add that to PRs in the future.

**Pull request merged**
