### PR TITLE
Add more details about TDP entity and API curation

### PR DESCRIPTION
**Pull request by shrutiyer**
- Fix the links into variables

Question for the tech writer: Are you able to test the links? We want to variable-ize all the links to keep it in one place to quickly check and update them as new versions come in.

### CODE REVIEW

**Comment by shrutiyer** [comment]
@karinepires @csterwa @visomar @tiagofernandez check out the MR for any additions

**Review by csterwa — APPROVED** [review]
I think it is a bit strange to put the Backstage links under AAR in variables. Should they be put somewhere else?

**Review by visomar — APPROVED** [review]

**Comment by RichardJJG** [comment]
2 reasons not to put all those links in variables:

1. It's harder to spot when they fall out of date within VS Code. Link-checking extensions won't work.
2. It's difficult to see where the links go at all -- the engineer/tech writer will have to keep checking `template_variables.yaml`.

**Comment by shrutiyer** [comment]
@RichardJJG so for tech writers, is it recommended to not do this? Sounds like it makes things difficult for y'all? Our team was trying to do this because we don't how many links to update (for example for all the SCG links) when we have released a new version of that other product. Is there a recommendation to not have stale but still functional links?

**Comment by RichardJJG** [comment]
> @RichardJJG so for tech writers, is it recommended to not do this? Sounds like it makes things difficult for y'all? Our team was trying to do this because we don't how many links to update (for example for all the SCG links) when we have released a new version of that other product. Is there a recommendation to not have stale but still functional links?

I sympathize with wanting to keep links fresh for minimal effort. There is a [2-year-old ticket](https://jira.eng.vmware.com/browse/CDF-18843) for being able to create links that always redirect to the latest version.

Is the 2.1 version number the main problem here? If so, you could just keep that number in a variable. That's what we did with the [TAP version variable](https://github.com/pivotal/docs-tap/blob/main/template_variables.yaml#L3).

**Comment by shrutiyer** [comment]
Sounds good. Thanks for the suggestion and I have made the updates to follow the pattern other components are following. Ready for your review @RichardJJG

**Comment by RichardJJG** [comment]
> Sounds good. Thanks for the suggestion and I have made the updates to follow the pattern other components are following. Ready for your review @RichardJJG

Thanks, @shrutiyer -- that does look easier to handle going forward.

**Comment by shrutiyer** [comment]
No other branches as of now. Thanks!

**Pull request merged**
