### PR TITLE
Update install-air-gap.hbs.md

### PR DESCRIPTION
**Pull request by dhadukk**
Remove username password from the value file and provide secret

# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

### CODE REVIEW

**Comment by mdc81** [comment]
@dhadukk steps to create the secret also should be included or referenced from TBS docs.

**Comment by mdc81** [comment]
looks good

**Comment by snneji** [comment]
Hi @dhadukk, is this just for 1.5 or should it be cherry picked to another version?

**Comment by dhadukk** [comment]
This change is only required for TAP 1.5

**Pull request merged**
