### PR TITLE
ESBACK-387 - Adds API documentation for Tanzu Developer Portal Configurator

### PR DESCRIPTION
**Pull request by chinigo**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

These docs are targeted for 1.7 only. No need to cherry-pick to any other branches.

### CODE REVIEW

**Comment by RichardJJG** [comment]
@chinigo, what coding language is this [snippet](https://github.com/pivotal/docs-tap/pull/3093/files#diff-422c7ea0591a2a78d8fa06193bfa766ae8157fb864d58c5bdd889422a277cf27R12)?

**Comment by chinigo** [comment]
> @chinigo, what coding language is this [snippet](https://github.com/pivotal/docs-tap/pull/3093/files#diff-422c7ea0591a2a78d8fa06193bfa766ae8157fb864d58c5bdd889422a277cf27R12)?

@RichardJJG it's Typescript.

Good look, I'm working on some further improvements to these API docs. I'll add the `typescript` hint to this snippet in a new PR:

> \`\`\`typescript
> …
> \`\`\`

**Comment by RichardJJG** [comment]
@chinigo, thanks. Is it worth me editing this doc in the meantime, or will it change so substantially soon that I should just wait for the next PR?

**Comment by chinigo** [comment]
You could make the change now if you want. I'll make sure to retain it in my next revision.

Thanks!

**Pull request merged**
