### PR TITLE
Updated with new sbom feature

### PR DESCRIPTION
**Pull request by miketeve**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?  None

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

### CODE REVIEW

**Comment by YugangW** [comment]
@miketeve Could you help us resolve the conflict? Thanks.

**Comment by miketeve** [comment]
@YugangW when i resolve them, my only way of saving is by merging.  I'm going to click merge.  We can always correct things with another PR.

**Comment by miketeve** [comment]
ah, okay - it just merged the conflict!  Still needs someone to commit this PR!

**Comment by YugangW** [comment]
Thanks, @miketeve. It has been merged.

**Pull request merged**
