### PR TITLE
Update services docs to make use of class claims

### PR DESCRIPTION
**Pull request by teddyking**
Class Claims are a new feature in TAP 1.4 and this commit updates the corresponding documentation to make use of them.

Which other branches do you want a technical writer to cherry-pick this PR to (if any)? None - these changes are only relevant from TAP 1.4 onwards.

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

### CODE REVIEW

**Comment by teddyking** [comment]
Hi there, as part of this change we'll also need to update the corresponding diagrams on the "Set up services for consumption by developers" and "Consume services on Tanzu Application Platform" pages. How can we go about doing that? I don't think I have access to the source image for those diagrams 🤔 

I've attached a rough diagram depicting the changes to make:

updated-diagram-stk

* Change 1 - Update the text from `$ tanzu service claim create` to `$tanzu service class-claim create`
* Change 2 - Create a new box for `ClassClaim`. The green arrow from App Operator should now point to the `ClassClaim` and there should be green arrow from `ClassClaim` to `ResourceClaim`.

Everything else on the diagram should remain the same.

Thanks!

**Comment by HenryBorys** [comment]
@teddyking Because we don't have the original, we need to submit a ticket to Content Ops for this. I can do it if you like.

**Comment by teddyking** [comment]
@HenryBorys Ah ok, yes please that would be great, thanks!

**Comment by HenryBorys** [comment]
Okay, I've put in the ticket: https://jira.eng.vmware.com/browse/CO-4163

**Comment by HenryBorys** [comment]
@teddyking What versions of the docs will this updated image apply to?

**Comment by teddyking** [comment]
Thanks @HenryBorys - this change only applies to TAP version 1.4+ so no need to backport it to earlier branches.

**Comment by HenryBorys** [comment]
@teddyking Cool! Thanks!

**Pull request merged**
