### PR TITLE
Improve sigstore stack docs

### PR DESCRIPTION
**Pull request by elfotografo007**
Which other branches should this be merged with (if any)?
This change is intended for 1.4, 1.3.1 and 1.3.0.

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @elfotografo007

**Comment by elfotografo007** [comment]
Hi Richard, do I need to perform something else to get these changes into 1.3.0 and 1.3.1?

**Comment by RichardJJG** [comment]
@elfotografo007, no, a writer will cherry-pick your changes for you after they've finished any edits.

**Comment by elfotografo007** [comment]
Cool, thanks.

**Pull request merged**
