### PR TITLE
[1.8.0] release notes: Add notes for buildpacks+stacks

### PR DESCRIPTION
**Pull request by arjun024**
- Links are under the assumption that [this PR](https://github.com/pivotal/docs-tanzu-buildpacks/pull/1904) will be merged and published.

---
#### > Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

This is only relevant for 1.8

### CODE REVIEW

**Comment by arjun024** [comment]
@johnnyr0x, @anthonydahanne /@pivotal-david-osullivan - please review

@Maintainers - please wait for a review before merging

**Comment by RichardJJG** [comment]
@arjun024, I've put this back in draft mode to prevent accidental premature merging

**Review by johnnyr0x — COMMENTED** [review]
Looks good

**Comment by anthonydahanne** [comment]
LGTM too. Thanks @arjun024

**Comment by arjun024** [comment]
@RichardJJG /Maintainers Please Merge :)

**Pull request merged**
