### PR TITLE
Removed SCA scan results, SCA scan summary...

### PR DESCRIPTION
**Pull request by miketeve**
... and store-specific known issues

Which other branches should this be merged with (if any)? 1.0

### CODE REVIEW

**Comment by a-peek4** [comment]
Hi @miketeve Can you confirm if the changes in the red box are the ones you want to keep with your commit?
Screen Shot 2022-04-08 at 2 53 24 PM

**Comment by miketeve** [comment]
@a-peek4 i'm not super great at reading that.  if that is just showing that those files are deleted then, yes, that's what we want!

**Comment by a-peek4** [comment]
Great, thanks. Yes that is what that shows.

**Comment by a-peek4** [comment]
Merging bc it came in before docs freeze

**Pull request merged**
