### PR TITLE
Added label part-of in workload sample of example1 docker workload sample

### PR DESCRIPTION
**Pull request by sendjainabhi**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

added label part-of in workload sample of example1 docker workload sample

### CODE REVIEW

**Comment by YugangW** [comment]
Hi @sendjainabhi, It seems this PR includes multiple commits from different contributors, and there are numerous unresolved conflicts. Would you prefer me to close this one so that you can submit a new, clean PR specifically focused on the intended changes? Thanks!

**Comment by sendjainabhi** [comment]
> Hi @sendjainabhi, It seems this PR includes multiple commits from different contributors, and there are numerous unresolved conflicts. Would you prefer me to close this one so that you can submit a new, clean PR specifically focused on the intended changes? Thanks!

@YugangW - can you please suggest which branch i should choose for new PR ? is it main ?

**Comment by sendjainabhi** [comment]
will open a new pr for clean merge

**Comment by YugangW** [comment]
> > Hi @sendjainabhi, It seems this PR includes multiple commits from different contributors, and there are numerous unresolved conflicts. Would you prefer me to close this one so that you can submit a new, clean PR specifically focused on the intended changes? Thanks!
> 
> @YugangW - can you please suggest which branch i should choose for new PR ? is it main ?

Yes, main would be the best. Thanks!

**Pull request closed without merging**
