### PR TITLE
docs(Source Controller): Adding the Source Controller Know Issue for …

### PR DESCRIPTION
**Pull request by seagomezar**
…1.5.0 and 1.5.1. Also Moving to the proper sections the ESO Issue and flix

# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

### CODE REVIEW

**Review by rashedkvm — COMMENTED** [review]
Question: I see external-secrets update and Tanzu Source Controller known issue in this PR. I recall reviewing a separate PR for external-secrets update. Is this PR correct? Should it rebase?

**Comment by kcoriordan** [comment]
@seagomezar Is this ready to merge?

**Review by rashedkvm — APPROVED** [review]

**Comment by RichardJJG** [comment]
Hi, @seagomezar, this PR deletes [a known issue from the TAP GUI section](https://github.com/pivotal/docs-tap/pull/2482/files#diff-9707337ff7669eeeef77ed0ea8d0331063a18d427f3a85ac04244bd8faa19979L618). Is that deliberate? I ask because the PR does not seem otherwise related to TAP GUI.

**Comment by RichardJJG** [comment]
@seagomezar, you say to cherry-pick to 1-5-0. This [issue you mention](https://github.com/pivotal/docs-tap/pull/2482/files#diff-9707337ff7669eeeef77ed0ea8d0331063a18d427f3a85ac04244bd8faa19979R37) doesn't appear in the TAP v1.4 release notes. 

If the issue was introduced in TAP v1.5.0, and it's now resolved in the exact same version, we won't call it out as "resolved" in the v1.5.1 patch.

**Comment by RichardJJG** [comment]
Queries resolved on Slack: https://vmware.slack.com/archives/C02P2UZHJ4F/p1683628617295059

**Pull request merged**
