### PR TITLE
Few small updates to STK and services

### PR DESCRIPTION
**Pull request by teddyking**
Hi there,

This pr contains a few small updates to consuming services section.

Thanks
Ed

Which other branches should this be merged with (if any)? N/A - target for TAP 1.2 only.

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @teddyking

**Comment by teddyking** [comment]
Thanks for the notes @HenryBorys. Regarding your second point - yes essentially I wanted to convey that the list of Operators integrate well with TAP without any further modifications or configuration on the users behalf. Also noted Re: "in GitHub" usage. Thanks!

**Comment by HenryBorys** [comment]
@teddyking  Is it enough to just say, "The following list of Kubernetes operators expose APIs that integrate well with Tanzu Application Platform"? Or should we say, "The following list of Kubernetes operators expose APIs that integrate well with Tanzu Application Platform without user modifications or configurations." And if you prefer the latter, consider whether it may in some cases require user modifications, in which case, we shouldn't say that. Let me know. For now we have the first option on the site.

**Comment by teddyking** [comment]
I think the first option works, thanks!

**Pull request merged**
