### PR TITLE
List of packages for view profile modified

### PR DESCRIPTION
**Pull request by andmagom**
Hello,
There were missing marks for the view profile. So:

-  I added tick mark for Source Controller for view profile
-  I added tick mark for Flux Source Controller for view profile

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @andmagom, does this change apply to the v1.1 docs as well as v1.2 (`main` branch)?

**Comment by andmagom** [comment]
Hello @RichardJJG, yes it applies to v1.1 too

**Comment by andmagom** [comment]
Do I have to create a new MR ?

**Comment by RichardJJG** [comment]
> Do I have to create a new MR ?

No, a writer will handle the cherry-pick.

**Pull request merged**
