### PR TITLE
Add caution when clusterimagepolicy not defined

### PR DESCRIPTION
**Pull request by DennyHoang**
Adding a caution for some behavior that should be highlighted.

This can also be cherry-picked for 1.2.x docs.

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @DennyHoang

**Comment by DennyHoang** [comment]
@RichardJJG Should I create another PR to have it merged into 1.2.x docs or will you folks do it?

**Comment by RichardJJG** [comment]
> @RichardJJG Should I create another PR to have it merged into 1.2.x docs or will you folks do it?

We'll cherry-pick for you

**Comment by DennyHoang** [comment]
Someone pointed out to me also that there is a spelling mistake on "publically" -> "publicly"

**Comment by RichardJJG** [comment]
> Someone pointed out to me also that there is a spelling mistake on "publically" -> "publicly"

Yep, I saw that, thanks. We'll fix all spelling errors, etc.

**Pull request merged**
