### PR TITLE
Added prerequisites and modified install instructions.

### PR DESCRIPTION
**Pull request by dhadukk**
Modified docs for beta-2. Added cert-manager pre req.

### CODE REVIEW

**Comment by jncd** [comment]
Hi @dhadukk 
Thanks for this PR! Are you ready to have it merged in? 
I'm afraid that you'll have to sort out these conflicts before I can merge for you.

Going forward, I realize that this file will be changing a lot. Best for you to make a PR with your changes at the end of every day. Don't wait for perfection. 😀

**Comment by dhadukk** [comment]
@jncd Could you please help me to merge PR now? I have resolved conflicts.
Not sure if ## Packages in Tanzu Application Platform v0.2 in install-general.md is required or not. Please feel free to remove it if not needed.

**Comment by jncd** [comment]
@dhadukk Thanks so much for all the conflict resolution. 
There was still one conflict. See screenshot. I resolved it by taking your version. (The difference was in the `-n`, I think.) Make sure that I did the right thing. Thanks!
Screen Shot 2021-09-30 at 9 48 44 AM

**Comment by dhadukk** [comment]
Yes @jncd you did the right thing. Thanks a lot.

**Pull request merged**
