### PR TITLE
Adds a release note for TAP GUI around auto TLS

### PR DESCRIPTION
**Pull request by mstergianis**
Signed-off-by: Michael Stergianis <mstergianis@vmware.com>

Which other branches do you want a technical writer to cherry-pick this PR to (if any)?
None

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

### CODE REVIEW

**Comment by andreizimin** [comment]
@mstergianis @RichardJJG - should we just focus on the "new" version - how it should look like?

**Comment by mstergianis** [comment]
Not opinionated if we show both the old format and the new one, or just the new one.

Honestly I think my preference would be a diff format, something like
```diff
--- old-tap-values.yaml	2023-01-03 15:21:05.110897726 -0500
+++ new-tap-values.yaml	2023-01-03 15:21:17.147698490 -0500
@@ -1,8 +1,8 @@
 tap_gui:
   app_config:
     app:
-      baseUrl: http://tap-gui.INGRESS-DOMAIN/
+      baseUrl: https://tap-gui.INGRESS-DOMAIN/
     backend:
-      baseUrl: http://tap-gui.INGRESS-DOMAIN/
+      baseUrl: https://tap-gui.INGRESS-DOMAIN/
       cors:
-        origin: http://tap-gui.INGRESS-DOMAIN/
+        origin: https://tap-gui.INGRESS-DOMAIN/
```

So maybe I should have done that in the first place. Does our docs site have the ability to render a diff like it does yaml? That'd be nice :smile:

**Comment by RichardJJG** [comment]
@mstergianis, @andreizimin 

> Does our docs site have the ability to render a diff like it does yaml?

No, but I've been asking for code syntax highlighting for a long time. There is a [JIRA issue](https://jira.eng.vmware.com/browse/CDF-20121) you can vote for.

> should we just focus on the "new" version - how it should look like?

I think that would be neatest, given the limitations.

**Comment by mstergianis** [comment]
Excellent thanks @RichardJJG

**Pull request merged**
