### PR TITLE
[VSEE-649] Update VSE troubleshooting scanning docs

### PR DESCRIPTION
**Pull request by rxl7906**
Update the VSE troubleshooting scanning docs with:
* get logs from scan-pod 
* kubectl-describe sourcescan or imagescan
* tanzu workload command to get all logs from containers

Which other branches should this be merged with (if any)?
N/A

### CODE REVIEW

**Comment by rxl7906** [comment]
@HenryBorys I apologize for the short notice but could you merge this before the 1.2.0 doc freeze happens thank you.

**Comment by HenryBorys** [comment]
@rxl7906 Thank you. I have merged. @a-peek4 will go over this.

**Comment by HenryBorys** [comment]
@rxl7906 Is this exclusively for 1.2 or does it apply to any other release?

**Comment by rxl7906** [comment]
@HenryBorys this is for 1.2 and main

**Pull request merged**
