### PR TITLE
Added Ingress Configuration details to TAP-GUI

### PR DESCRIPTION
**Pull request by krisapplegate**

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @krisapplegate

**Comment by RichardJJG** [comment]
Which values in this command are placeholders, @krisapplegate?

```
tanzu package installed update  tap --package-name tap.tanzu.vmware.com --version 0.4.0 --values-file tap-values-file.yml -n tap-install
```

Just `tap-values-file`? Or maybe `package-name` too?

**Comment by krisapplegate** [comment]
> Which values in this command are placeholders, @krisapplegate?
> 
> ```
> tanzu package installed update  tap --package-name tap.tanzu.vmware.com --version 0.4.0 --values-file tap-values-file.yml -n tap-install
> ```
> 
> Just `tap-values-file`? Or maybe `package-name` too?

In that command there are none actually. The only thing I'd update is the version (to 1.0.0 or whatever the GA version is set to be)

**Comment by RichardJJG** [comment]
Thanks, will do.

**Pull request merged**
