### PR TITLE
Add note on amr observer not support self-signed registries

### PR DESCRIPTION
**Pull request by derwei**
# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

Please cherry pick this to all other 1-6-x branches

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

### CODE REVIEW

**Comment by a-peek4** [comment]
@derwei let me know when this is ready to merge. It currently says that merging is blocked pending a review. Thank you!

**Comment by derwei** [comment]
Hi @a-peek4 !
I've had my team take a look and it looks good to them. I've removed the draft and this is good to be merged.

However I'm not sure how to get an approval on this MR....

**Review by a-peek4 — APPROVED** [review]

**Comment by a-peek4** [comment]
Oh, I know why we can't merge it. 1-6-1 branch is closed since that release has passed. The active branches for 1.6 are currently 1-6-2 and 1-6-3. Is there an easy way for you to change which branch this PR is targeting?

**Comment by derwei** [comment]
oops! let me re-do this. I'll work off the 1-6-3 branch.

**Pull request closed without merging**
