### PR TITLE
Update release-notes.hbs.md

### PR DESCRIPTION
**Pull request by tshaine**
https://jira.eng.vmware.com/browse/TAD-613

Which other branches should this be merged with (if any)?
1-2

### CODE REVIEW

**Comment by chinigo** [comment]
LGTM @tshaine.

**Comment by RichardJJG** [comment]
Hi, @tshaine, did these changes arrive in TAP v1.2.0 or are they changes that will arrive in v1.2.1? (They must be specific to one patch)

**Comment by chinigo** [comment]
These changes dropped in v1.2.0. Have we opened this PR against the wrong branch? Should we re-open it against the [1-2 branch](https://github.com/pivotal/docs-tap/tree/1-2) instead?

**Comment by tshaine** [comment]
@RichardJJG and @chinigo -- I'll close this PR out and open a new one against 1-2

**Comment by tshaine** [comment]
Closing this PR in favor of https://github.com/pivotal/docs-tap/pull/1423

**Pull request closed without merging**
