### PR TITLE
Update release-notes.hbs.md

### PR DESCRIPTION
**Pull request by Braundo**
added a known issue to TAP GUI (PSTAR-910 & TANZUSC-1470)

### CODE REVIEW

**Comment by Braundo** [comment]
This known issue impacts all released versions of TAP GUI, so we may want to also add this every other release branch.

**Comment by RichardJJG** [comment]
Thanks, @Braundo

**Comment by RichardJJG** [comment]
@Braundo, I should cherry-pick this all the way back to the TAP v1.0 docs, I'm guessing? The known issue description suggests that it's relevant to all released versions of TAP GUI.

**Comment by Braundo** [comment]
> 

That is correct, but wasn't 100% sure the process for putting this on all previous docs versions.

**Comment by RichardJJG** [comment]
@Braundo, that's fine, thanks. 
The process is: you submit your PR to the most recent branch it applies to (usually `main`) and you say in a comment on the PR where a writer should cherry-pick the changes to after the writer has finished editing. The available branches, and their corresponding docs versions, are listed on the repo README page.

**Pull request merged**
