### PR TITLE
Adding most content for Security Analysis

### PR DESCRIPTION
**Pull request by miketeve**
Added content and images along with an image to the SCC vulnerabilities table

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @miketeve, will this PR apply only to the TAP v1.3 docs?

**Comment by miketeve** [comment]
Yes only for 1.3

**Comment by miketeve** [comment]
Accidentally closed!

**Comment by RichardJJG** [comment]
@miketeve, I'm not seeing any files now (I guess you because you closed the PR?)

**Comment by miketeve** [comment]
@RichardJJG - had a bit of a snafu with this one.  ultimately submitted the changes thru this pr: https://github.com/pivotal/docs-tap/pull/1742

**Comment by RichardJJG** [comment]
> @RichardJJG - had a bit of a snafu with this one. ultimately submitted the changes thru this pr: #1742

Ahh, okay, that's fine

**Pull request closed without merging**
